### ISSUE TITLE
Additional default folders: Sent, Delete, Inbox, Archives, Templates, Drafts, Archives, Junk

### ISSUE THREAD

**Issue by ovari** [cleidigh/Localfolder-TB#11]
When creating a `LocalFolders` Account, in addition to the `Trash` and `Outbox` folders, can the following default folders also be created: `Templates`, `Drafts`, `Archives`?

a) This can help with future integration with the [Mail Merge add-on](https://addons.thunderbird.net/addon/mail-merge/), as it uses `Templates` and `Drafts` folders

b) When creating these folders after a `LocalFolders` Account has been created the icons are standard folder icons, not the special icons

`Local Folders` = Default Thunderbird Account
`LocalFolders` = Default LocalFolders add-on Account
![image](https://user-images.githubusercontent.com/17465872/54948552-01c43980-4f91-11e9-8c73-9a75a953f9d4.png)

What do you think?

Thank you

Edit:

When creating a `LocalFolders` Account, in addition to the Trash and Outbox folders, can the following default folders also be created:
`Trash`, (done)
`Sent`, 
`Delete`, 
`Drafts`, (missing from image below)
`Outbox`,  (done)
`Inbox`, 
`Archives`, 
`Templates`, 
`Junk`

![image](https://user-images.githubusercontent.com/17465872/56252840-28434380-60fd-11e9-816a-5c299b9c8d7e.png)
Screenshot from the [FolderFlags add-on](https://addons.thunderbird.net/addon/folderflags/)

**Comment by cleidigh** [comment]
@ovari 
Couple of things...
- I have zero exposure to Exchange, so keep that in mind I have no background in that.
- It sounds like you are describing use case that could be important (supporting Exchange for users?)
- Other than the extra folders specifically mentioned in this issue, perhaps we should discuss the use case more generally to look at it from high level.
- I did a quick check last night and if you create Drafts or Templates under any folder, it does appear to pick up the icons.  The caveat is that it appears Thunderbird needs to be restarted as something is perhaps only done at startup.  If this is the case, we could add those folders at the main folder creation time and they should pick up the icons.
- I don't know if there is any logic behind these folders that is required but perhaps not supported?

**Comment by ovari** [comment]
1. You can currently use Exchange Accounts in Thunderbird for free with the [ExQuilla for Exchange add-on](https://addons.thunderbird.net/addon/exquilla-exchange-web-services/).
2. A use-case is creating emails with IMAP accounts where there is no Internet access (or Thunderbird is in Offline Mode) using the [Mail Merge add-on](https://addons.thunderbird.net/addon/mail-merge/).
3. The [Mail Merge add-on](https://addons.thunderbird.net/addon/mail-merge/) uses `Templates` and `Drafts` folders. Perhaps in future, the [Mail Merge add-on](https://addons.thunderbird.net/addon/mail-merge/) may also enable the source folder to be defined to any folder.
4. Can icons, if available, be picked-up at creation time without the need to restart Thunderbird? Yes, when a `LocalFolders` Account is created these folders should also be created.
5. Don't understand your question.

**Comment by cleidigh** [comment]
@ovari 
Finally found the account error Re: folder creation - looks like this bug has existed for some time
Now no restarts, create special folders with flags/correct icons

**Comment by ovari** [comment]
@cleidigh well done!

**Comment by cleidigh** [comment]
I still have a bunch of cleanup/debug removal et cetera
Also have to do new manifest locales, hoping to get it out a few days.
 if you want to test drive it:
https://github.com/cleidigh/Localfolder-TB/blob/localfolders-v2-update/xpi/localfolders-2.0.0-b3-tb.xpi

**Comment by cleidigh** [comment]
Implemented:
v2.0.0
