### ISSUE TITLE
Les dossiers locaux dysfonctionnent / EN : Local folders are failing

### ISSUE THREAD

**Issue by Lorand-fr** [cleidigh/Localfolder-TB#28]
Version originale en FR
Bonsoir,
j'ai créé plusieurs "nouveaux" dossiers locaux (un pour chacune des associations auxquelles je contribue bénévolement). Le premier semble fonctionner normalement. Mais les autres n'affichent pas le contenu des messages mais un message tronqué : "Ou vous pouvez ajouter une exception..." en bleu et un bouton "Réessayer" non fonctionnel. Je ne sais pas ce que je dois faire pour afficher le contenu des messages que j'y ai transférés alors qu'il semble qu'ils sont bien là. Merci d'avance pour toute aide.
Cordialement,

Version EN with Systran
Good evening,
i have created several "new" local files (one for each of the associations to which I volunteer). The first one seems to work normally. But others don't display the content of the messages, but a truncated message: "Or you can add an exception..." in blue and a "Retry" button not functional. I don't know what to do to display the content of the messages I've transferred to it when it seems they're there. Thank you in advance for any help.
Cordially,

**Comment by cleidigh** [comment]
@Lorand-fr 
Thanks for transferring it here, much easier to debug !
First it would be good to know exactly what you are using:
Thunderbird Version
OS
anything else you think might be relevant.  

I can make a slightly educated interpretation of your post.  The message you refer to actually sounds to me like a system warning/question dialogue probably having to do with a firewall.  I say that because the phrase "...add an exception" is typically about a firewall rule.  Would it be possible to do a screenshot?  What I can tell you is that I know that dialogue is not contained within the extension and therefore has to be from some external source probably the system.

Is the local folder on a network drive perhaps?  
Cheers
Christopher

**Comment by Lorand-fr** [comment]
Bonjour,
Voici les renseignements demandés : 

Thunderbird : 68.4.1
OS : Windows10
LocalFolder : Dossiers locaux + 6 (name : "DL xxxxx") => 2 dossiers fonctionnent ("Dossiers locaux" et "DL perso"
![LocalFolder-Exception](https://user-images.githubusercontent.com/60117946/72963477-b8629780-3db7-11ea-9bf4-71c323988ee9.jpg)

Merci de votre aide.
Cordialement,
Roland

**Comment by cleidigh** [comment]
@Lorand-fr 
Is it possible for you to see the local folders from the OS?  I mean can you browse to them without problem?  I still leaning towards a permission issue, but I don't think we have enough information yet.

**Comment by Lorand-fr** [comment]
Bonjour,
je peux consulter les dossier (cf copie d'écran ci-dessus). Je peux voir la liste des messages (sujet, date, expéditeur...) mais lorsque je clique sur le message pour en afficher le contenu, j'ai systématiquement le message affiché dans la copie d'écran sauf pour le premier dossier local créé.
Donc :
- Dossiers locaux fonctionnent
- DL perso fonctionne
- DL coreg / DL codep 41 / DL FFCT et DL-NouanRando affichent toujours le message "Ou vous pouvez ajouyter une exception..." avec le bouton "Réessayer" totalement inactif.

Thunderbird 68.4.2 / OW windows10 à jour / extensions (Aucune mise à jour disponible) : 
- Envoi différé
- Lightning
- LocalFoders
- Reminderfox
- Signature Switch

**Comment by cleidigh** [comment]
@Lorand-fr  Bonjour
I thought of a couple more questions:
- Where to the local folders reside, all on your machine?  On a network share/drive?
- How did you get the messages into the new local folders especially the problematic ones?

Possible experiments:
- Create a new local folder for one of the problematic ones in the same location as one works
- Try the "Repair Folder" option under the folder context Menu "Properties"
- Check the debug console for any errors after trying to look  at messages

**Comment by Lorand-fr** [comment]
Bonjour,

j'ai enfin trouvé...
Sur ma machine, j'ai créé des dossiers correspondants à mes dossiers locaux et portant le même non. Dans ces dossiers, j'ai créé un sous-dossier pour accueillir les messages Thunderbird de mes dossiers locaux. Enfin presque... Les dossiers dans mes documents débutent par une icône pour identifier les associations auxquelles je contribue. Et c'est cet icône qui plante le système ! C'est à dire qu'au lieu de "🚴 FFCT-Centre", j'ai (re)nommé le dossier "FFCT-Centre" par exemple. 

Conclusion : LocalFolder-TB n'aime pas les caractères trop spéciaux ou spécieux.

Merci à tous ceux qui ont tenté de m'aider.

Traduction automatique (via Systran.net) / Automatic translation (via Systran.net)

Hello,

I finally found...
On my machine, I created folders that match my local folders and carry the same no. In these folders, I created a subfolder to receive Thunderbird messages from my local folders. Almost... The folders in my documents start with an icon to identify the associations I contribute to. And it's this icon that crashes the system! That is, instead of "🚴 FFCT Center", I have (re)named the file "FFCT Center" for example.

Conclusion: LocalFolder-TB doesn't like characters that are too special or specious.

Thanks to everyone who tried to help me.
