### ISSUE TITLE
the added 'feature' of added folders is detrimental for some uses

### ISSUE THREAD

**Issue by BrrrKnee2** [cleidigh/Localfolder-TB#34]
I have used LocalFolders for local network storage of emails to keep them organized and off of the cloud.
The more recent add of inserting folders other than 'trash' may be useful in other cases, but as I use it, 'trash' is the only useful standard folder.  All others I set up as I need.  I have absolutely no need for an out-box/ unsent sub-folder.  Please modify this to that end.
thank you, excellent tool, should be core Tbird functionality.

**Comment by cleidigh** [comment]
@BrrrKnee2 
working on the last two versions the trash and outbox are not optional
Thunderbird seems to expect them
I may be able to hide them 
@cleidigh
