### ISSUE TITLE
LocalFolders upgrade requires unexpected permissions

### ISSUE THREAD

**Issue by rthouvenin** [cleidigh/Localfolder-TB#41]
I currently have version 2.0.2 installed on Thunderbird 68.10, and Thunderbird suggests that I could upgrade the add-on but I need to grant the following permissions:

 -  Access your data for all websites
 -  Access browser tabs

What does it mean? Why would this add-on require these permissions and why not before?
I found the [permissions documentation](https://developer.thunderbird.net/add-ons/mailextensions/supported-webextension-api), and it makes me think the descriptions I pasted above are poorly worded, but it still not clear what it means.
I know nothing about Thunderbird development, sorry if this is a basic question :)

Thanks for your work!

**Comment by cleidigh** [comment]
@rthouvenin 
thanks for the question, you are correct the permissions are not exactly crystal clear.
basically everything is related to an increased ,granular security model.
the code for localfolders requires the use of "privileged APIs", specifically
filesystem manipulation as well as a content tab.  the file system should be obvious
it has always been Required, the tab permission is necessary for the account settings additions

if you add other extensions especially under 78+ you will see other examples of this.
unfortunately the permission text is not under the extensions Control.

Christopher

**Comment by rthouvenin** [comment]
Thanks for the clarification! I will address the wording issue with Thunderbird or whichever Mozilla lib this falls under (I suspect this is because it is shared with Firefox)
