### ISSUE TITLE
Update for TB 91+

### ISSUE THREAD

**Issue by q-pa** [cleidigh/Localfolder-TB#50]
Will there be an update that works with TB 91+ soon?

**Comment by jobisoft** [comment]
Does this work for you?
https://github.com/cleidigh/Localfolder-TB/pull/51#issuecomment-917031761

**Comment by q-pa** [comment]
Many thanks for the quick reply. My OS does not yet provide TB 91, though. Maybe someone else might jump in to test...?

**Comment by tidebre67** [comment]
@jobisoft , John, did a quick test and as far as i can see v3.2 works with TB v91.

**Comment by jobisoft** [comment]
Thanks for your feedback, it is available on ATN already :-)
