### ISSUE TITLE
Local folder on mac M1 does not seem to work

### ISSUE THREAD

**Issue by Tl-aem** [cleidigh/Localfolder-TB#55]
I can create a new local folder, I can create subfolder but I can't transfert any message on it.

I try with Onedrive, dropbox and local.

It work without problem with the basic local folder

**Comment by wsmwk** [comment]
> I can create a new local folder, I can create subfolder but I can't transfert any message on it.

@Tl-aem Do you still see this problem??

**Comment by Tl-aem** [comment]
It's ok now.

**Comment by cleidigh** [comment]
@Tl-aem 
Excellent, glad to hear this is resolved.
I will close.
@cleidigh
