### ISSUE TITLE
TB 102 compatibility

### ISSUE THREAD

**Issue by engdarkalchemist** [cleidigh/Localfolder-TB#56]
Please, could you verify Tb 102 compatibility?

**Comment by cleidigh** [comment]
@engdarkalchemist 
After a long hiatus for personal reasons, I am back and working on LocalFolders.
Please watch 
#58 
I will have a first beta shortly.
@cleidigh

**Comment by cleidigh** [comment]
@engdarkalchemist 
First beta:
- #58 
@cleidigh
