### ISSUE TITLE
Cannot read pop-up window

### ISSUE THREAD

**Issue by w9087r** [cleidigh/Localfolder-TB#59]
Hello - new user here.
When trying to create a local folder, the pop-up windows comes up all white. Cannot read anything.
See attached image for how it looks on my screen.
Is there a workaround for this issue?
Thank you
<img width="632" alt="LocalFolders" src="https://user-images.githubusercontent.com/110350896/182040143-1bf6c23f-1939-43d5-b307-c2b4019b99d3.png">
.

**Comment by cleidigh** [comment]
@w9087r 
Late response...
Can you indicate versions, os etc.
Also are you using any themes?
@cleidigh

**Comment by cleidigh** [comment]
@w9087r 
Here is a beta that fixes dark mode.

https://github.com/cleidigh/Localfolder-TB/blob/v3.3.1/xpi/localfolders-3.3.1-b1-tb.xpi

@cleidigh

**Comment by cleidigh** [comment]
@w9087r 
Here is the new release that fixes dark mode : 
https://addons.thunderbird.net/EN-us/thunderbird/addon/localfolder/?src=ss
@cleidigh

**Comment by cleidigh** [comment]
Closed with v3.3.2
