### ISSUE TITLE
Using a dark theme makes GUI unreadable

### ISSUE THREAD

**Issue by cjdg** [cleidigh/Localfolder-TB#60]
On dark theme is impossible to see gui

![imagen](https://user-images.githubusercontent.com/5726836/189237354-08a53db3-470e-495e-be5e-4cdc95061273.png)

**Comment by cleidigh** [comment]
@cjdg 
Oh that does not look good...
Probably CSS changes, will look into it.
Thanks for the catch.
@cleidigh

**Comment by cleidigh** [comment]
@cjdg 
Found it.
Not a great screenshot, but you can see the fixed theme colors.
I will post a beta that you can use until I can push through a release.

@cleidigh 

<img width="960" alt="2022-09-12-16-39-58 " src="https://user-images.githubusercontent.com/25272315/189755524-4e7e0c34-9427-44a7-9a13-14cba30c8c12.png">

**Comment by cjdg** [comment]
Ok will check it and let it know!

**Comment by cleidigh** [comment]
@cjdg 
Had to fixup a few elements to improve dark aspects.
I also bumped compatibility to 105
Let me know what you think.
@cleidigh 

https://github.com/cleidigh/Localfolder-TB/blob/v3.3.1/xpi/localfolders-3.3.1-b1-tb.xpi

**Comment by cleidigh** [comment]
@cjdg 
I just released 3.3.2 that fixes Dark mode:
https://addons.thunderbird.net/EN-us/thunderbird/addon/localfolder/?src=ss
@cleidigh

**Comment by cjdg** [comment]
Just tested and its amazing!!! Great job!!!

**Comment by cleidigh** [comment]
@cjdg 
Excellent, thanks !
Of course there were many manual tweaks for contrast etc.
Glad you think it looks good.
@cleidigh

**Comment by cleidigh** [comment]
Closed with v3.3.2
