### ISSUE TITLE
How to set Local Directory

### ISSUE THREAD

**Issue by LilyHiggins** [cleidigh/Localfolder-TB#63]
I am trying to create a new local folder using the LocalFolders add on in Thunderbird. How do you enter or choose a local directory to set up the folder?

Thanks!

**Comment by cleidigh** [comment]
@LilyHiggins 
A local folder is considered an account so new local folders are added under the Account Settings tab. The Account actions drop down will have a new entry "Add local folder" which will open the configuration dialog.
@cleidigh

**Comment by LilyHiggins** [comment]
Thanks! Yes, but how do I know what directory to choose to put there? I tried
C:\Users\XXX\AppData\Roaming\Thunderbird\Profiles\XXX\Mail\Local Folders but that didn't work. I wasn't sure what "Local Directory" I'd use to create a new local folder.
Thanks for the help.

**Comment by cleidigh** [comment]
@LilyHiggins 
The directory you choose is almost arbitrary. The standard LF under TB is in the AppData dir.  I like to put my additional LFs in a directory that is outside that and safe, backed up etc.  It can even be a NAS location.
Cheers
@cleidigh

**Comment by LilyHiggins** [comment]
Great - thanks so much. So can it even be a file that I create just for that storage like C:\Users\XXX\Documents\TBArchive or something like that?
Thanks again!

**Comment by cleidigh** [comment]
@LilyHiggins 
Exactly!
...btw reviews always welcome  ;-)
@cleidigh

**Comment by LilyHiggins** [comment]
Great - thanks so much. And I will try to get it all working and post a review when I can! Thanks again!

**Comment by cleidigh** [comment]
@LilyHiggins 
Great 
@cleidigh

**Comment by cleidigh** [comment]
@LilyHiggins 
Hopefully you got things working?
If so I think we can close?
@cleidigh

**Comment by LilyHiggins** [comment]
Yes, thanks! I haven't had too much time to play around with the Local
Folders, but yes, I think we can close. Sorry I didn't get back to you
sooner. I'll repost a question if I have another. Thanks!

**Comment by cleidigh** [comment]
@LilyHiggins 
Great, cheers
Christopher
