### ISSUE TITLE
Impossible to create/add/move/copy in the new created Localfolders

### ISSUE THREAD

**Issue by cdem55** [cleidigh/Localfolder-TB#64]
TB 102.2.1

when I try to copy or move an email from a local thunderbird default folder to the new "localfolders", the destination folder stays empty
Any idea ?

Thanks

**Comment by cleidigh** [comment]
@cdem55 
Can you id the os and LF versions.
Also did the selected folders get created?
Any errors in the console log?
Did you try restarting Thunderbird?
@cleidigh
