### ISSUE TITLE
How do I delete a LocalFolder?

### ISSUE THREAD

**Issue by symonjim** [cleidigh/Localfolder-TB#66]
Sorry. Newbie question for which I can't seem to find an answer.

I created some LocalFolder test folders in Thunderbird but can't find what I need to do to delete them. 

Thanks,

Jim

**Comment by symonjim** [comment]
Localfolders 3.3.2

**Comment by cleidigh** [comment]
Under Account actions, highlight the LF you want to remove and use the Remove account option.
@cleidigh

**Comment by symonjim** [comment]
thanks. worked.
