### ISSUE TITLE
unable to copy messages to local subfolders

### ISSUE THREAD

**Issue by organdi** [cleidigh/Localfolder-TB#69]
Hi, I created a new locla folder account and added subfolders (months). In the past I used to copy 100 mails to sub folder. Now even 1 it does not copy and when I select 2 i have this message enclosed a print screen.
![BUG LOCAL FOLDER](https://user-images.githubusercontent.com/129671061/229357002-0848afde-fed3-4c05-9be2-03cd21136d1b.jpg)

**Comment by cleidigh** [comment]
@organdi 
Can you give your os, tb and LocalFolders version info.
Also can you check the console for errors?
@cleidigh

**Comment by organdi** [comment]
Hi,

I use windows family 11, version 21H2, build 22000.1761
Local Folder : 3.3.2

You will find enclosed the error console, the thunderbird dashboard and 
also the report sent as this issue (trying to copy 2 messages to sub 
folder on local folders) created a crash
Sincères Salutations/Best Regards
Denis



250bis/2b rue du Flocon
59200 Tourcoing
tél : +33 3 20 70 49 02
Mobile : +33 6 73 26 35 23
e-mail : ***@***.***
Le 02/04/2023 à 18:15, Christopher Leidigh a écrit :

**Comment by cleidigh** [comment]
@organdi 
Do I understand correctly that TB actually crashed?
Was this the first time you used LF?
If you saw the LF created with the required trash and outbox folders, then it was already writing ok.
Were you ever able to check the console?
Also the error popup was saying you need to compress because of space, correct?
@cleidigh

**Comment by organdi** [comment]
Hi,

no it's not the first time I use LF.

What is not normal is that it can not copy because it says that the 
subfolder as no free space...
But I just created it and it is empty!!!!

I already have existing old folders and subfolders which created in 
previous TB versions.
And it was working fine.
But this time, with new folders and subfolders it fails and crashes

Maybe I should uninstall and install it again?
Sincères Salutations/Best Regards
Denis



250bis/2b rue du Flocon
59200 Tourcoing
tél : +33 3 20 70 49 02
Mobile : +33 6 73 26 35 23
e-mail : ***@***.***
Le 06/04/2023 à 15:13, Christopher Leidigh a écrit :

**Comment by cleidigh** [comment]
@organdi 
I didn't see a console output attachment, could it have failed to load?
Did you try try to recreate the LF?
@cleidigh

**Comment by organdi** [comment]
hi,

sorry for my late answer, but now it's fine and I will explain what I found.

I tried several options.
First I deleted the local account, and restarted TB. No change
I tried to copy messages and the same warning message is poping up, 
informing there's not enough space that I must to delete files...
I remove Local Folder addons, restarted TB, install the addons again and 
restarted again.
I try to copy 1 message. Nothing happened. No pop-up message, no crash, 
but also nothing copied.
So I tried another way, copying mails to main local folder and then copy 
thoses messages to the local folder I created with your addon.
The messages were correctly copied to the main local folder, but not the 
new local folder I created...

In the debug file, I noticed that there's a conflict in account number 2.
As I use for this computer an addon called "Manually sort folders", I 
thought that maybe this created the issue.
So I unactivated this addon, and now it works fine.

The conflict comes from the other addon "Manually sort folders"

Hope it could help!

Sincères Salutations/Best Regards
Denis



250bis/2b rue du Flocon
59200 Tourcoing
tél : +33 3 20 70 49 02
Mobile : +33 6 73 26 35 23
e-mail : ***@***.***
Le 10/04/2023 à 18:04, Christopher Leidigh a écrit :

**Comment by cleidigh** [comment]
@organdi 
That's interesting, I am a bit surprised that the MSF extension interferes that much. Does the Original Local folder work?
Have you posted to the author?
@cleidigh

**Comment by cleidigh** [comment]
@organdi 
Can I close?
@cleidigh

**Comment by organdi** [comment]
HI,

yes we can close
Sincères Salutations/Best Regards
Denis



250bis/2b rue du Flocon
59200 Tourcoing
tél : +33 3 20 70 49 02
Mobile : +33 6 73 26 35 23
e-mail : ***@***.***
Le 30/04/2023 à 23:49, Christopher Leidigh a écrit :

**Comment by cleidigh** [comment]
@organdi 
Thanks 
Salud 
@cleidigh
