### ISSUE TITLE
Add missing keyboard shortcuts (accesskey)

### ISSUE THREAD

**Issue by ovari** [cleidigh/Localfolder-TB#7]
For en-US locale:
Add keyboard shortcut (accesskey) "N" to "Name:"
Add keyboard shortcut (accesskey) "D" to "Directory:"

![image](https://user-images.githubusercontent.com/17465872/54886069-cf0a3a80-4ed7-11e9-9836-1e32132ce4d1.png)

Add keyboard shortcuts (accesskey) to any other dialog boxes, menus which are missing keyboard shortcuts (accesskey).

Add appropriate keyboard shortcuts (accesskey) to other locales.

What do you think?

Thank you

**Comment by cleidigh** [comment]
@ovari 
Actually there are several other keyboard accessibility issues, particularly important since I am disabled also.
I just have to make some judgment calls on what we do now versus downline.  I have to spread my timeout.
do you think it's worth doing this now for the next version Release, or get the Hungarian now?

**Comment by ovari** [comment]
Release frequently. The Agile method. Release version 1.1, 1.2, 1.3, ... 1.9, 2.0, 2.1, ...

This can help you to reach the 2.0 release sooner, which some consider to be the first stable release.

Also, people may prefer this as they will see active development.

**Comment by cleidigh** [comment]
I agree in general, I'm just thinking of the Q on ATN

So assuming it takes several more days to add accesskeys, and perhaps the directories (assuming that we define squarely)  should we wait?

**Comment by ovari** [comment]
If there are small and frequent changes it is easy to check, so LocalFolders should be updated on [ATN](https://addons.thunderbird.net/) quickly. For example, see the [CardBook Version History](https://addons.thunderbird.net/addon/cardbook/versions/).

**Comment by cleidigh** [comment]
I will look at what I can do by tomorrow with access keys.  Other than that I think you had some missing locale strings I should include.

Following on, let's define the exchange requirements so we can see with related.

**Comment by cleidigh** [comment]
Addressed by #12 
See comments on Folder Name
