### ISSUE TITLE
Adding possibility to Open/Close LocalFolders

### ISSUE THREAD

**Issue by fabiosardi** [cleidigh/Localfolder-TB#71]
is it possible to implement the opening and closing of an archive?
it would be very useful in case you wanted to archive old mail as a historian and then reopen it if you needed to consult it.
Currently if I try to recreate a LocalFolder account on a folder that already has content the files are replaced with empty versions and old data is lost.
To see an old archive you have to create an account, close TB, manually copy the old folders and then reopen TB.

Thank you.

**Comment by cleidigh** [comment]
@fabiosardi 
I am not seeing any data erasure when doing this. What is necessary is to close TB and reopen so it reindexes to see the folders.
Can you give any more detail on the deletion of files. Also platforms and versions.
@cleidigh

**Comment by fabiosardi** [comment]
I tried to recreate the problem but it didn't do it again, it didn't delete my data, probably last time I had only selected the flag to recreate the structure, good this way you can open and close the archives if needed, thanks.

**Comment by cleidigh** [comment]
@fabiosardi 
Excellent!
@cleidigh
